### ISSUE TITLE
OpenSAFELY Reports mangles fancy quotes

### ISSUE THREAD

**Issue by benbc** [opensafely-core/reports#550]
[A report](https://reports.opensafely.org/reports/increase-in-hepatitis-cases-in-children-a-rapid-opensafely-analysis-to-support-the-national-incident/) contains this text in the [Methods](https://reports.opensafely.org/reports/increase-in-hepatitis-cases-in-children-a-rapid-opensafely-analysis-to-support-the-national-incident/#Methods) section:

> To allow rapid analysis, codelists for identifying hepatitis and GI illness were pragmatically developed using the SNOMED CT hierarchy; hepatitis was defined as any child code of âInflammatory disease of liverâ (SNOMED CT: 128241005) and GI illness defined as any child code of âDisorder of the digestive systemâ (SNOMED CT: 53619000).

The text in the corresponding [published output on Job Server](https://jobs.opensafely.org/hepatitis-in-children-related-to-the-pandemic/hepatitis_in_children/outputs/71/release/project_report.html) looks like this:

> To allow rapid analysis, codelists for identifying hepatitis and GI illness were pragmatically developed using the SNOMED CT hierarchy; hepatitis was defined as any child code of “Inflammatory disease of liver” (SNOMED CT: 128241005) and GI illness defined as any child code of “Disorder of the digestive system” (SNOMED CT: 53619000).

Note that the quotes around the code names have been mangled.

Is it possible to fix this?

This request comes from @LFISHER7 in [Slack](https://bennettoxford.slack.com/archives/C02HJTL065A/p1700059043291359).

**Comment by benbc** [comment]
cc @LFISHER7 -- this is now fixed.

**Comment by LFISHER7** [comment]
Thanks. I've refreshed the linked report, but the formatting is still the same, do I need to do anything else to update it?

**Comment by benbc** [comment]
@ghickman ? :point_up:

**Comment by ghickman** [comment]
I'm seeing the same thing, even with the magic `?force-update=1` trick to bypass caching, back to the drawing board 😩

**Comment by ghickman** [comment]
@LFISHER7 – this specific report should now be fixed, could you double-check it's working for you as well?

If the quotes are still mangled, can you try with [this URL](https://reports.opensafely.org/reports/increase-in-hepatitis-cases-in-children-a-rapid-opensafely-analysis-to-support-the-national-incident/?force-update=1) too?  (it's got `force-update=1` on the end)

🤞
